-- Supabase Database Schema for AirDraw
-- Run this in your Supabase SQL Editor

-- ═══════════════════════════════════════════════════════
-- STORAGE BUCKET SETUP (Optional - for storing images in Supabase Storage)
-- ═══════════════════════════════════════════════════════
-- If you want to use Supabase Storage instead of base64:
-- 1. Go to Storage section in Supabase Dashboard
-- 2. Create a new bucket named 'gallery-images'
-- 3. Make it public
-- 4. Set file size limit to 50MB
-- 5. Run the storage policies at the bottom of this file

-- ═══════════════════════════════════════════════════════
-- STEP 1: DROP CONFLICTING STORED PROCEDURES
-- ═══════════════════════════════════════════════════════
-- Drop ALL overloaded versions of save_gallery_item to avoid
-- "Could not choose the best candidate function" errors

DROP FUNCTION IF EXISTS public.save_gallery_item(
  p_user_id TEXT,
  p_dataurl TEXT,
  p_timestamp TEXT,
  p_name TEXT,
  p_drawingdata TEXT,
  p_textitemsdata JSONB,
  p_shapeitemsdata JSONB
);

DROP FUNCTION IF EXISTS public.save_gallery_item(
  p_user_id TEXT,
  p_dataurl TEXT,
  p_timestamp TEXT,
  p_drawingdata TEXT,
  p_textitemsdata JSONB,
  p_shapeitemsdata JSONB
);

-- Drop any other overloads that may exist
DROP FUNCTION IF EXISTS public.save_gallery_item CASCADE;
DROP FUNCTION IF EXISTS public.execute_sql CASCADE;

-- ═══════════════════════════════════════════════════════
-- STEP 2: RECREATE GALLERY TABLE
-- ═══════════════════════════════════════════════════════

DROP TABLE IF EXISTS gallery CASCADE;

-- Create gallery table to store user artwork
-- dataURL column stores either:
--   - Supabase Storage public URL (if storage is configured)
--   - Base64 dataURL (fallback if storage is not configured)
CREATE TABLE gallery (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       TEXT NOT NULL,
  dataURL       TEXT NOT NULL,
  "timestamp"   TEXT NOT NULL,
  drawingData   TEXT,
  textItemsData JSONB DEFAULT '[]',
  shapeItemsData JSONB DEFAULT '[]',
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════
-- STEP 3: ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════

ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;

-- Drop existing policies before recreating
DROP POLICY IF EXISTS "Users can view own gallery"   ON gallery;
DROP POLICY IF EXISTS "Users can insert own gallery" ON gallery;
DROP POLICY IF EXISTS "Users can update own gallery" ON gallery;
DROP POLICY IF EXISTS "Users can delete own gallery" ON gallery;

CREATE POLICY "Users can view own gallery"   ON gallery FOR SELECT USING (true);
CREATE POLICY "Users can insert own gallery" ON gallery FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own gallery" ON gallery FOR UPDATE USING (true);
CREATE POLICY "Users can delete own gallery" ON gallery FOR DELETE USING (true);

-- ═══════════════════════════════════════════════════════
-- STEP 4: INDEXES
-- ═══════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS gallery_user_id_idx    ON gallery(user_id);
CREATE INDEX IF NOT EXISTS gallery_created_at_idx ON gallery(created_at DESC);

-- ═══════════════════════════════════════════════════════
-- STEP 5: AUTO-UPDATE updated_at TRIGGER
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_gallery_updated_at ON gallery;

CREATE TRIGGER update_gallery_updated_at
  BEFORE UPDATE ON gallery
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ═══════════════════════════════════════════════════════
-- STEP 6: STORED PROCEDURE (single, canonical version)
-- ═══════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION save_gallery_item(
  p_user_id       TEXT,
  p_dataurl       TEXT,
  p_timestamp     TEXT,
  p_drawingdata   TEXT    DEFAULT NULL,
  p_textitemsdata  JSONB  DEFAULT '[]',
  p_shapeitemsdata JSONB  DEFAULT '[]'
)
RETURNS TABLE (
  id             BIGINT,
  user_id        TEXT,
  dataURL        TEXT,
  "timestamp"    TEXT,
  drawingData    TEXT,
  textItemsData  JSONB,
  shapeItemsData JSONB,
  created_at     TIMESTAMPTZ,
  updated_at     TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  INSERT INTO gallery (
    user_id,
    dataURL,
    "timestamp",
    drawingData,
    textItemsData,
    shapeItemsData
  )
  VALUES (
    p_user_id,
    p_dataurl,
    p_timestamp,
    p_drawingdata,
    p_textitemsdata,
    p_shapeitemsdata
  )
  RETURNING *;
END;
$$;

-- ═══════════════════════════════════════════════════════
-- STEP 7: ADD name COLUMN (migration — safe to run on existing table)
-- ═══════════════════════════════════════════════════════

ALTER TABLE gallery ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'Untitled';

-- ═══════════════════════════════════════════════════════
-- STEP 8: REFRESH PostgREST SCHEMA CACHE
-- ═══════════════════════════════════════════════════════

NOTIFY pgrst, 'reload schema';
SELECT pg_notify('pgrst', 'reload schema');

-- ═══════════════════════════════════════════════════════
-- STEP 8: VERIFY (optional debug check)
-- ═══════════════════════════════════════════════════════

-- Check table columns
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'gallery'
ORDER BY ordinal_position;

-- Confirm only ONE save_gallery_item function exists
SELECT proname, pronargs, proargnames
FROM pg_proc
WHERE proname = 'save_gallery_item';

-- ═══════════════════════════════════════════════════════
-- STORAGE POLICIES (Optional - Only if using Supabase Storage)
-- ═══════════════════════════════════════════════════════
-- Run these after creating the 'gallery-images' bucket in the dashboard

DROP POLICY IF EXISTS "Public read access to gallery-images"    ON storage.objects;
DROP POLICY IF EXISTS "Authenticated upload to gallery-images"  ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own images"             ON storage.objects;

-- Anyone can view images (needed for gallery display)
CREATE POLICY "Public read access to gallery-images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'gallery-images');

-- Authenticated users can upload images
CREATE POLICY "Authenticated upload to gallery-images"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'gallery-images' AND
    auth.role() = 'authenticated'
  );

-- Users can only delete their own images (folder = user_id)
CREATE POLICY "Users can delete own images"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'gallery-images' AND
    auth.uid()::text = (storage.foldername(name))[1]
  );

-- Grant storage permissions to authenticated users
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT ALL ON SCHEMA storage TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO authenticated;
