-- Supabase Database Schema for AirDraw
-- Run this in your Supabase SQL Editor

-- STORAGE BUCKET SETUP (Optional - for storing images in Supabase Storage)
-- If you want to use Supabase Storage instead of base64:
-- 1. Go to Storage section in Supabase Dashboard
-- 2. Create a new bucket named 'gallery-images'
-- 3. Make it public
-- 4. Set file size limit to 50MB
-- 5. Run the storage policies below (lines 145-155)

-- Drop existing table to recreate with correct schema
DROP TABLE IF EXISTS gallery CASCADE;

-- Create gallery table to store user artwork
-- dataURL column can store either:
-- - Supabase Storage public URL (if storage is configured)
-- - Base64 dataURL (fallback if storage is not configured)
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  dataURL TEXT NOT NULL, -- Stores Supabase Storage URL or base64 dataURL
  "timestamp" TEXT NOT NULL,
  drawingData TEXT,
  textItemsData JSONB DEFAULT '[]',
  shapeItemsData JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;

-- Create policy: Users can only see their own gallery items
CREATE POLICY "Users can view own gallery" ON gallery
  FOR SELECT USING (true);

-- Create policy: Users can only insert their own gallery items  
CREATE POLICY "Users can insert own gallery" ON gallery
  FOR INSERT WITH CHECK (true);

-- Create policy: Users can only update their own gallery items
CREATE POLICY "Users can update own gallery" ON gallery
  FOR UPDATE USING (true);

-- Create policy: Users can only delete their own gallery items
CREATE POLICY "Users can delete own gallery" ON gallery
  FOR DELETE USING (true);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS gallery_user_id_idx ON gallery(user_id);
CREATE INDEX IF NOT EXISTS gallery_created_at_idx ON gallery(created_at DESC);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER update_gallery_updated_at
  BEFORE UPDATE ON gallery
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Debug: Check table structure
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'gallery' 
ORDER BY ordinal_position;

-- Refresh PostgREST schema cache
NOTIFY pgrst, 'reload schema';

-- Alternative cache refresh
SELECT pg_notify('pgrst', 'reload schema');

-- Create stored procedure to bypass PostgREST cache
CREATE OR REPLACE FUNCTION save_gallery_item(
  p_user_id TEXT,
  p_dataurl TEXT,
  p_timestamp TEXT,
  p_drawingdata TEXT DEFAULT NULL,
  p_textitemsdata JSONB DEFAULT '[]',
  p_shapeitemsdata JSONB DEFAULT '[]'
)
RETURNS TABLE (
  id BIGINT,
  user_id TEXT,
  dataURL TEXT,
  "timestamp" TEXT,
  drawingData TEXT,
  textItemsData JSONB,
  shapeItemsData JSONB,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  INSERT INTO gallery (
    user_id, 
    dataURL, 
    "timestamp", 
    drawingData, 
    textItemsData, 
    shapeItemsData
  )
  VALUES (
    p_user_id,
    p_dataurl,
    p_timestamp,
    p_drawingdata,
    p_textitemsdata,
    p_shapeitemsdata
  )
  RETURNING *;
END;
$$;

-- Generic SQL execution function to bypass PostgREST
CREATE OR REPLACE FUNCTION execute_sql(sql_query TEXT, params TEXT[] DEFAULT '{}')
RETURNS TABLE (
  id BIGINT,
  user_id TEXT,
  dataURL TEXT,
  "timestamp" TEXT,
  drawingData TEXT,
  textItemsData JSONB,
  shapeItemsData JSONB,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  EXECUTE format(sql_query, params);
END;
$$;

-- ═══════════════════════════════════════════════════════
-- STORAGE POLICIES (Optional - Only if using Supabase Storage)
-- ═══════════════════════════════════════════════════════
-- Run these policies after creating the 'gallery-images' bucket

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Public read access to gallery-images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated upload to gallery-images" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own images" ON storage.objects;

-- Allow public read access to images in gallery-images bucket
-- This allows anyone to view images (needed for gallery display)
CREATE POLICY "Public read access to gallery-images"
ON storage.objects FOR SELECT
USING (bucket_id = 'gallery-images');

-- Allow authenticated users to upload images
CREATE POLICY "Authenticated upload to gallery-images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'gallery-images' AND
  auth.role() = 'authenticated'
);

-- Allow users to delete their own images
CREATE POLICY "Users can delete own images"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'gallery-images' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Grant necessary permissions
GRANT USAGE ON SCHEMA storage TO authenticated;
GRANT ALL ON SCHEMA storage TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA storage TO authenticated;
